--- 
dist: xenial
jobs: 
  include: 
     -language: java
     before_script:
          - cd server
     script:
          - ./gradlew test
     -language: node_js
     node_js:
          - lts/*
     before_script:
           - cd ~/client
           - npm ci
     script:
          - npm test

          

