auth0:
    audience: https://BoredGamerzDev
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://dev-z2irz81c.us.auth0.com/
    datasource:
        username: root
        password: PWfields!
        url: jdbc:mysql://localhost:3306/boredgamerzdb
    jpa:
        hibernate:
            ddl-auto: update
