auth0:
    audience: https://BoredGamerzDev
spring:
    sendgrid:
        key:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://dev-z2irz81c.us.auth0.com/
                    clientId: Z5nnmXJO8bA1UeqgvjchD5bGaq1N75m4
                    clientSecret:
    datasource:
        username: root
        password:
        url: jdbc:mysql://35.202.6.200:3306/boredgamerzdb
    jpa:
        hibernate:
            ddl-auto: update
