auth0:
    audience: http://BoredGamerzDev
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://dev-z2irz81c.us.auth0.com/
    datasource:
        username:
        password:
        url: jdbc:mysql://----:3306/boredgamerzdb
    jpa:
        hibernate:
            ddl-auto: update
